DevCycleHQ/android-client-sdk

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEdgeDBApi.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEdgeDBApiClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCOptions.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/Request.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/EdgeDB.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Project.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ProjectSettings.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt

- add DVCOptions attribute of enableEdgeDB
- add EdgeDB saveEntity calls
- Add ProjectSettings class to Project so we can determine whether or not EdgeDB is enabled for a project
- Add unit tests & assertions to make sure `enableEdgeDB` is being sent correctly

Android EdgeDB

---

README.md
android-client-sdk/build.gradle
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/BucketedUserConfig.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/DVCUser.kt

- move `@JsonIgnoreProperties(ignoreUnknown = true)` to apply to the entire BucketedUserConfig Model
- version bump to 1.0.8 to release

Fix to handle new top level fields on the Bucketed User Config

---

android-client-sdk/build.gradle
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/EventQueue.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
kotlin-example/src/main/java/com/devcycle/example/KotlinApplication.kt

Create a close method on the DVCClient which:
- closes the SSE connection
- Closes off the event queue and clears the scheduled flush jobs
- Flushes remaining events

Dvc 4866 close method

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Variable.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
kotlin-example/src/main/java/com/devcycle/example/MainActivity.kt

- add a better signature for the variable.onUpdate method which accepts a plain function rather than a DVCCallback object.
- mark the old signature as deprecated

feat: change callback signature for variable onUpdated to plain function

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/EventQueue.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Variable.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt

- make fields that are required to exist on the variable object non-optional
- fix initializing variables with the wrong type by using provided default values

 variable type fixes

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DVCSharedPrefs.kt

When identifyUser is called, if the user is not anonymous, clear ANONYMOUS_USER_ID after we've fetched the config

Clear ANONYMOUS_USER_ID when identifying a user

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DVCSharedPrefs.kt

- When resetting user, clear ANONYMOUS_USER_ID before building a new user object so that the new user has a different anonymous ID
- If reset fails, set anon user id back to previous value
- Update dvcSharedPrefs.getCache to return null if stored value is null

Clear ANONYMOUS_USER_ID when resetting user

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/User.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DVCSharedPrefs.kt

when initializing the DVCClient, compare and store anonymous user id to SharedPrefs to not create multiple anon users for same device.

[DVC-5123] android store read anon user id on initialize

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt

remove the Anon user Id management to `saveUser` to ensure the changes are not persistent even when called outside of the `onInitialized` callback

[DVC-5186] change anon user id management flow

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCOptions.kt

The configCacheTTL was defaulting to 0, so if a DVCOptions object was built without passing the configCacheTTL param it would disable the cache. 
Set configCacheTTL to null in the Options object, and let the DVCClient handle defaulting the value if it's not passed

Fix configCacheTTL default

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt

Previously whenever a non-anonymous user was idenified we would clear the cached anon ID. Instead we will only overwrite it when a new anon ID is generated (ie. via reset)

Don't clear anonymous user ID when identifying a user

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/UserAndCallback.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/exception/DVCVariableException.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/BucketedUserConfig.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ReadOnlyVariable.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Variable.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt

-Separate parsing of variables on the config into their own data class (ReadOnlyVariable)
-Update all the callbacks for identify etc. that were returning a map of full variable objects to just return "ReadOnlyVariables"
-Ensure defaultValue is always set on the regular `Variable` class by making it required
- this should hopefully fix the bug with the onUpdate not always being fired when reverting to defaults.

fix: parse variables from config as their own data class, attempt to fix onUpdate

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCApi.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEdgeDBApiClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEventsApiClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/Request.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/interceptor/AuthorizationHeaderInterceptor.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
java-example/src/main/java/com/devcycle/javaexample/JavaApplication.java
kotlin-example/src/main/java/com/devcycle/example/KotlinApplication.kt

This is to be consistent across all our various SDKs we have aligned on `sdkKey` over `envKey` or `environmentKey`

DVC-6219 Rename occurrences of envKey and environmentKey with sdkKey

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt

Wrap `close` methods of `EventSource` in coroutines to prevent exceptions on network calls on the main thread

fix: wrap close eventsource calls in coroutine in activity callbacks

---

android-client-sdk/src/main/AndroidManifest.xml
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCApiClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEdgeDBApiClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/Request.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/exception/NoNetworkException.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/interceptor/NetworkConnectionInterceptor.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/EventQueueTests.kt

- on unknown exceptions, don't retry the request (e.g. `UnknownHostException` when no internet connection)
- add interceptor to okhttp builder to throw an error immediately if the device is not connected to the internet

fix: on unknown exceptions, dont retry requests

---

.github/workflows/unit-test.yml
android-client-sdk/build.gradle
android-client-sdk/proguard-rules.pro
android-client-sdk/src/main/AndroidManifest.xml
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/PopulatedUser.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DVCSharedPrefs.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties
java-example/build.gradle
java-example/gradle/wrapper/gradle-wrapper.properties
java-example/src/main/AndroidManifest.xml
kotlin-example/build.gradle
kotlin-example/gradle/wrapper/gradle-wrapper.properties
kotlin-example/src/main/AndroidManifest.xml
kotlin-example/src/main/java/com/devcycle/example/KotlinApplication.kt
kotlin-example/src/main/java/com/devcycle/example/MainActivity.kt

**Main problem**
The newest R8 strips a lot of stuff when its enabled.
I copied a ton of the details from here to add to our proguard consumer file:
https://github.com/square/retrofit/issues/3751
I also added a ton of protections around the jackson lib so that those types and files don't get stripped as well. 
Main item here too is making sure we `keep` the Android folder as it contains the coroutine schedule, objectmapper, and how we read configs locally and from the API
Other notes
* Force test apps to always run with R8 enabled so we catch these things earlier
* Update test apps to most recent version of gradle
* Update SDK to android 33 and newest Gradle 
* Update tests to handle new Android things which were failing

Upgrade to gradle 8.0.2, fix proguard rules for r8

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/eventsource/EventSource.java

- add safety around start() in EventSource to catch exception

chore: add safety around start() in EventSource

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DVCSharedPrefs.kt

- remove redundant `commit()` call 
- `commit()` will apply changes to SharedPreferences synchronously which may cause slower performance

fix: allow async saving of SharedPreferences

---

.github/workflows/unit-test.yml
android-client-sdk/build.gradle
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DevCycleClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DevCycleOptions.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DevCycleClientTests.kt
build.gradle

- Added two new options to the DevcycleOptions class
- The apiProxyUrl and eventsApiProxyUrl options will override the urls for the config request as well as events requests to enable proxying

feat: apiProxyUrl and eventsApiProxyUrl options

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/eventsource/EventSource.java

- fixes onClosed throwing error up to the client when it should be catching it

fix: wrapped throwable function in a try catch

---

.github/workflows/release.yml
android-client-sdk/build.gradle
gradle/wrapper/gradle-wrapper.properties

- changed target of maven publish to central portal

fix: use latest version of maven publish to publish to central portal

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/EventQueue.kt

change `scheduleJob` in `EventQueue` into a `nullable Job`, handle optional in `close()`

fix: crash in EventQueue from scheduleJob

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/model/PopulatedUser.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/api/PopulatedUserTests.kt

- if any `context` properties are null, catch them and use defaults

fix: catch any usage of context if context properties are undefined

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ConfigVariable.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/JSONMapper.kt

- fix: allow JSON deserialization of the DevCycle User Config to handle new properties
- added explicitly to the ConfigVariable classes
- added globally to the JSON Mapper

fix: allow JSON deserialization of the DevCycle User Config to handle new properties

---

android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DevCycleClientTests.kt
build.gradle

- chore: adds some unit tests to ensure successful config parsing when extra properties are added at different levels (root vs nested of existing properties) on the Bucketed User Config

chore: add tests for extra properties successfully parsing

---

.github/workflows/unit-test.yml

Potential fix for [https://github.com/DevCycleHQ/android-client-sdk/security/code-scanning/1](https://github.com/DevCycleHQ/android-client-sdk/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will specify the minimal permissions required for the workflow to function correctly. Based on the workflow's steps, it only needs to read the repository contents to check out the code and run tests. Therefore, we will set `contents: read` as the permission.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DevCycleClient.kt

- fix: use a cached config (if available), if identify user request fails

fix: use cached config if identify user fails

---

android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DevCycleClientTests.kt

- added test for invalid config

chore: add test for invalid config

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/model/BucketedUserConfig.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ConfigVariable.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/DevCycleUser.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/EdgeDB.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Environment.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ErrorResponse.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Feature.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Project.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/ProjectSettings.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/SSE.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/model/Variable.kt

The JSON parsing library was audited to ensure unknown properties are ignored globally.
*   It was confirmed that `JSONMapper.kt` is configured with `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` set to `false`, which globally ignores unknown JSON properties during deserialization.
*   Consequently, all redundant `@JsonIgnoreProperties(ignoreUnknown = true)` annotations were removed from the following model classes:
*   `BucketedUserConfig.kt`
*   `Variable.kt`
*   `ConfigVariable.kt` (6 instances across abstract and concrete classes)
*   `SSE.kt`
*   `ProjectSettings.kt`
*   `Project.kt`
*   `Feature.kt`
*   `ErrorResponse.kt`
*   `Environment.kt`
*   `EdgeDB.kt`
*   `DevCycleUser.kt`
*   Unused `import com.fasterxml.jackson.annotation.JsonIgnoreProperties` statements were also …

chore: cleanup unnecessary JSON properties and annotations

---

android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DevCycleClient.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DevCycleOptions.kt
android-client-sdk/src/main/java/com/devcycle/sdk/android/util/DevCycleLogger.kt
android-client-sdk/src/test/java/com/devcycle/sdk/android/util/DevCycleLoggerTests.kt

Implements configurable log level functionality, allowing developers to control logging verbosity in the DevCycle Android SDK.
- **DevCycleLogger.kt**: Added log level filtering with `minLogLevel` property and `setMinLogLevel()` method
- Added `isLoggable()` logic to filter messages based on minimum log level
- Supports all Android log levels: VERBOSE, DEBUG, INFO, WARN, ERROR, and NO_LOGGING
- Thread-safe implementation with `@Volatile` property
- **DevCycleOptions.kt**: Added `logLevel` configuration option
- New `logLevel()` builder method for setting log level in options
- Integrates with existing options pattern
- **DevCycleClient.kt**: Updated client initialization to respect log level configuration
- Options `logLevel` takes precedence over builder `logLevel`
- Logger only starts …

feat: Add configurable log level support to DevCycle Android SDK
